### ISSUE TITLE
EpicMusicPlayer_ MP3 File?! (Were is it?)

### ISSUE THREAD

**Issue by TRIDENTEIII** [Kiatra/EpicMusicPlayer_MP3#1]
Hello Kiatra i read the instuctions how to do to made my music for the EpicMusicplayer! I have 3 MP3 songs but there is no EpicMusicPlayer_MP3 in the EpicMusicPlayer folder in the Addons folder! And the is no "PlaylistCreator.vbs" file?!

I don't know how to make MP3 music files for the "EpicMusicPlayer! I missing things to do it!

Greetings from The Netherlands, WoW player from 2006: https://www.youtube.com/channel/UCjXYaE2UrYW6hFlOrzj8m0A/videos

**Comment by Kiatra** [comment]
the EpicMusicPlayer_MP3 is in this addon, you need to install it addtion to EpicMusicPlayer.

so:
Addons:

some addon
EpicMusicPlayer
EpicMusicPlayer_MP3
some other addon
